In [35]:
#import libraries
import numpy as np
import pandas as pd
import tflearn # tensorflow deep learning
import tensorflow as tf
import random
import json
import pickle
import nltk # natural langauge tool kit for nlp

In [36]:
#nltk.download('punkt')
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()

In [37]:
with open('data_new.json', 'r') as f:
    dataset = json.load(f)

In [38]:
#converting dictinary to pandas dataframe
df = pd.DataFrame.from_dict(dataset['data'])
df.head()

tag                                           patterns  \
0        Fire  [Fire, Flames, Choking, Suffocating, Burning, ...   
1  Earthquake  [Earthquake, Falling, shaking, moving, cracks,...   
2       Flood  [Water, Flood, flooding, submerge, drowning, r...   
3   Avalanche  [Snow, avalanche, snowpack, debris, slab, runo...   

                                           responses  
0  [Please consider the following measures- \n 1....  
1  [Please consider the following measures- \n 1....  
2  [Please consider the following measures- \n 1....  
3  [Please consider the following measures- \n 1....

In [39]:
#prepare training data
words = []
labels = []
docs_x = []
docs_y = []

for data in dataset["data"]: # dataset is dict. 'data' is key. dataset['data'] is array of dict. data is dict
    for pattern in data["patterns"]: #pattern is array element in dict element of array of dict
        w = nltk.word_tokenize(pattern)
        words.extend(w)
        docs_x.append(w)
        docs_y.append(data["tag"])

    if data["tag"] not in labels:
        labels.append(data["tag"])

ignore_words = ['?', '.', '!']
words = [stemmer.stem(w.lower()) for w in words if w not in ignore_words]
words = sorted(list(set(words)))
print(words)

['aftershock', 'avalanch', 'beacon', 'blaz', 'burn', 'chok', 'clos', 'crack', 'dam', 'debr', 'drown', 'earthquak', 'ep', 'fal', 'fir', 'flam', 'flood', 'heat', 'inferno', 'magintud', 'mov', 'prob', 'rainfal', 'richt', 'road', 'runout', 'rupt', 'seism', 'shak', 'shovel', 'slab', 'smok', 'snow', 'snowpack', 'storm', 'submerg', 'suffoc', 'swing', 'trem', 'tsunam', 'volcano', 'wat']


In [40]:
len(words)

42

In [41]:
labels = sorted(labels)
print(labels)

['Avalanche', 'Earthquake', 'Fire', 'Flood']


In [42]:
print(docs_x)

[['Fire'], ['Flames'], ['Choking'], ['Suffocating'], ['Burning'], ['Smoke'], ['heat'], ['burns'], ['blaze'], ['inferno'], ['volcano'], ['Earthquake'], ['Falling'], ['shaking'], ['moving'], ['cracks'], ['rupturing'], ['swinging'], ['aftershock'], ['tremor'], ['seismic'], ['epicenter'], ['tsunami'], ['magintude'], ['richter'], ['damage'], ['Water'], ['Flood'], ['flooding'], ['submerge'], ['drowning'], ['rainfall'], ['storm'], ['road', 'closure'], ['Snow'], ['avalanche'], ['snowpack'], ['debris'], ['slab'], ['runout'], ['beacon'], ['probe'], ['shovel']]


In [43]:
print(docs_y)

['Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Fire', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Earthquake', 'Flood', 'Flood', 'Flood', 'Flood', 'Flood', 'Flood', 'Flood', 'Flood', 'Avalanche', 'Avalanche', 'Avalanche', 'Avalanche', 'Avalanche', 'Avalanche', 'Avalanche', 'Avalanche', 'Avalanche']


In [44]:
wrds = [stemmer.stem(w) for w in docs_x[13]]
print(wrds)

['shak']


In [45]:
training = []
output = []

out_empty = [0 for _ in range(len(labels))] # intialise the a list out_empty with 0's with len = length of labels

for x, doc in enumerate(docs_x): # creates tuples of docs_x's index and values such that the index of the docs_x elements are stores in x and the element values are stored in the variable doc
    
	bag = []
    
	wrds = [stemmer.stem(w) for w in doc]

	for w in words:
		if w in wrds:
			bag.append(1)
		else:
			bag.append(0)
            
	output_row = out_empty[:]
	output_row[labels.index(docs_y[x])] = 1

	training.append(bag)
	output.append(output_row)

training = np.array(training)
output = np.array(output)

In [46]:
print(training)
print(output)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


In [47]:
# neural network model
tf.compat.v1.reset_default_graph() # creates a fresh new empty graph by clearing the nodes and operations of any previous computation

net = tflearn.input_data(shape=[None, len(training[0])]) # None specifies that the input layer can accept a variable number of samples., no of neurons in input layer= 32
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(output[0]), activation="softmax") #  no of neurons = 3
net = tflearn.regression(net)
# net = tflearn.softmax_categorical_crossentropy(net,output)
model = tflearn.DNN(net)

In [48]:
# neural network training
# try:
# 	model.load("model.tflearn")
# except:
model = tflearn.DNN(net)
model.fit(training, output, n_epoch=1000, batch_size=8, show_metric=True)
model.save("model_revised1.tflearn")  

Training Step: 5999  | time: 0.020s
| Adam | epoch: 1000 | loss: 0.00000 - acc: 0.9508 -- iter: 40/43
Training Step: 6000  | time: 0.022s
| Adam | epoch: 1000 | loss: 0.00000 - acc: 0.9557 -- iter: 43/43
--
INFO:tensorflow:C:\Users\manya\PycharmProjects\python\hackathon\model_revised1.tflearn is not in all_model_checkpoint_paths. Manually adding it.


In [49]:
def bag_of_words(s,words):
	bag = [0 for _ in range(len(words))]
	s_words = nltk.word_tokenize(s)
	s_words = [stemmer.stem(word.lower()) for word in s_words]

	for se in s_words:
		for i, w in enumerate(words):
			if w == se:
				bag[i] = 1

	return np.array(bag)

In [52]:
import speech_recognition as sr
import pyttsx3
import datetime

engine = pyttsx3.init('sapi5') #sapi5 is microsoft speech api
voices = engine.getProperty('voices') #main program
engine.setProperty('voice',voices[0].id)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()

def chat():
    print("Start Talking with the Bot (say quit to stop!)")
    while True:
        r=sr.Recognizer()
        inp=""
        def say():
            with sr.Microphone() as source:
                print("Listening...")
                r.pause_threshold = 0.5
                audio = r.listen(source)
            try:
                print("Recognizing...")
                inp = r.recognize_google(audio, language='en-in')
                print(f"You: {inp}\n")
        
            except Exception as e:
                print(e)
                print("Say that again please...")
                say()
        say()
        
        if inp.lower() == "quit":
            return "quit"
        
        results = model.predict(bag_of_words(inp, words).reshape(1, len(training[0]), 1))[0]
        print(results)
        results_index = np.argmax(results)
        tag = labels[results_index]

# Find the responses for the predicted label
        responses = None
        for tg in dataset["data"]:
            if tg['tag'] == tag:
                responses = tg['responses']
                break

# Find the response with the highest score
        max_response = None
        max_score = 0
        for response in responses:
            score = results[results_index]
            if score > max_score:
                max_response = response
                max_score = score
    
        print(max_response)
        speak(max_response)

ModuleNotFoundError: No module named 'speech_recognition'

In [51]:
#start chatting
chat()

Start Talking with the Bot (type quit to stop!)
You: I am covered in snow till my face
Please consider the following measures- 
 1. Try to stay on the surface of the snow by swimming or using other means to stay afloat.
 2. Try to hold onto a tree or other objects that will not be carried away by the avalanche.
 3. Cover your nose and mouth with your hand or a piece of clothing to protect yourself from the snow.
 4. If you are unable to move, try to stand as still as possible to conserve energy and avoid inhaling snow .
 5. Call the emergency number 108 to seek further help.



You: I am feeling dizzy
I didn't get that, please try again ! 
You: I am choking
Please consider the following measures- 
 1. Stay calm and do not panic 
 2. Sound the fire alarm and shout to alert others in the house 
 3. Call the local fire department immediately by dialing 101 or the emergency number in your area. Provide them with your address and details of the fire. 
 4. Close all doors and windows to cont

In [50]:
# #chat interface
# def chat():
    
# 	print("Start Talking with the Bot (type quit to stop!)")
# 	while True:
# 		inp = input("You: ")
# 		if inp.lower() == "quit":
# 			break

# 		results = model.predict([bag_of_words(inp,words)])[0]
# 		results_index = np.argmax(results) # returns the index of the maximum element in a 1-d array
# 		tag = labels[results_index]

# 		if results[results_index] > 0.5:
# 			for tg in dataset["data"]:
# 				if tg['tag'] == tag:
# 					responses = tg['responses']
# 			print(random.choice(responses))
# 			print("\n")

# 		else:
# 			print("I didn't get that, please try again ! ")